---
abstract: 'A POE Component to send packets to power on computers.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-WakeOnLAN
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  IO::Socket::INET: 0
  Net::IP: 0
  POE: 1
  Socket: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
