---
abstract: 'A POE Component to send packets to power on computers.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-WakeOnLAN
requires:
  IO::Socket::INET: 0
  Net::IP::Minimal: 0
  POE: 1.004
  Socket: 0
  perl: 5.006
resources:
  homepage: https://github.com/bingos/poe-component-wakeonlan
  repository: https://github.com/bingos/poe-component-wakeonlan.git
version: 1.04
